In [45]:
import os
import pickle
import numpy as np
import cv2
from PIL import Image
import matplotlib.pyplot as plt
from scipy import ndimage, misc
from sklearn import datasets
from sklearn.model_selection import train_test_split
%matplotlib inline
# 乱数シードを指定
np.random.seed(seed=0)

In [46]:
#CIFAR-10のデータセットのインポート
from keras.datasets import cifar10
(X_train, Y_train), (X_test, Y_test) = cifar10.load_data()
 
#CIFAR-10の正規化
from keras.utils import to_categorical
 
 
# 特徴量の正規化
X_train = X_train/255.
X_test = X_test/255.
 
# クラスラベルの1-hotベクトル化
Y_train = to_categorical(Y_train, 10)
Y_test = to_categorical(Y_test, 10)
 


In [62]:
# CNNの構築
import keras
from keras.models import Sequential
from keras.layers.convolutional import Conv2D, MaxPooling2D
from keras.layers.core import Dense, Dropout, Activation, Flatten
from keras.layers import GlobalAveragePooling2D
from keras.layers.normalization import BatchNormalization
import numpy as np
 
model = Sequential()
 
model.add(Conv2D(32, (3, 3), padding='same',input_shape=X_train.shape[1:]))
model.add(Activation('relu'))
model.add(BatchNormalization())
model.add(Conv2D(32, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
 
model.add(Conv2D(64, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(BatchNormalization())
model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Conv2D(128, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(Conv2D(128, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(BatchNormalization())
model.add(Conv2D(128, (3, 3)))
model.add(Activation('relu'))
model.add(Conv2D(128, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(256))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(10))
model.add(Activation('softmax'))

In [63]:
# コンパイル
model.compile(loss='categorical_crossentropy',optimizer='SGD',metrics=['accuracy'])
 
#訓練
history = model.fit(X_train, Y_train, epochs=20)

Epoch 1/20
1563/1563 [==============================] - 468s 299ms/step - loss: 1.7639 - accuracy: 0.3452
Epoch 2/20
1563/1563 [==============================] - 763s 488ms/step - loss: 1.3898 - accuracy: 0.5015
Epoch 3/20
1563/1563 [==============================] - 437s 279ms/step - loss: 1.2224 - accuracy: 0.5692
Epoch 4/20
1563/1563 [==============================] - 492s 315ms/step - loss: 1.1033 - accuracy: 0.6161
Epoch 5/20
1563/1563 [==============================] - 451s 288ms/step - loss: 1.0113 - accuracy: 0.6505
Epoch 6/20
1563/1563 [==============================] - 2443s 2s/step - loss: 0.9338 - accuracy: 0.6772
Epoch 7/20
1563/1563 [==============================] - 617s 395ms/step - loss: 0.8712 - accuracy: 0.7039
Epoch 8/20
1563/1563 [==============================] - 584s 374ms/step - loss: 0.8240 - accuracy: 0.7193
Epoch 9/20
1563/1563 [==============================] - 4658s 3s/step - loss: 0.7772 - accuracy: 0.7363
Epoch 10/20
1563/1563 [===========================

In [64]:
# モデルの保存
model.save('./CIFAR-10_2.h5')

 #評価 & 評価結果出力
print(model.evaluate(X_test, Y_test))

313/313 [==============================] - 13s 43ms/step - loss: 0.5980 - accuracy: 0.7970
[0.5979866981506348, 0.796999990940094]


In [113]:
cnt4=0.0
for i in range(100):
    if np.max(model(X_test[i:i+1]))>0.9:
        cnt4+=1.0
print(cnt4/100)
cnt5=0.0
for i in range(100):
    if np.max(model(X_test2[i:i+1]))>0.9:
        cnt5+=1.0
print(cnt5/100)

0.59
0.16


In [66]:
model(X_test2[0:100])

<tf.Tensor: shape=(100, 10), dtype=float32, numpy=
array([[4.62541193e-01, 4.61755320e-03, 3.28265965e-01, 3.04879975e-02,
        2.72943936e-02, 1.40618775e-02, 5.22054546e-03, 5.80909960e-02,
        3.96929756e-02, 2.97265593e-02],
       [4.94304113e-03, 8.54550221e-04, 1.32845357e-01, 1.92788854e-01,
        6.10333264e-01, 3.01418379e-02, 1.53740114e-02, 8.64098407e-03,
        2.34410632e-03, 1.73391611e-03],
       [4.29559703e-04, 9.89629552e-05, 2.06035636e-02, 1.82350110e-02,
        8.91513526e-01, 3.42903174e-02, 1.97262522e-02, 1.46413799e-02,
        2.53569218e-04, 2.07886289e-04],
       [7.93299638e-03, 8.21790159e-01, 4.46566939e-03, 5.16542792e-03,
        2.63733324e-03, 2.93764798e-03, 1.54477134e-02, 1.58546097e-03,
        6.58127107e-03, 1.31456360e-01],
       [1.32513151e-01, 1.01378346e-02, 5.92642501e-02, 4.63245995e-02,
        4.06351164e-02, 7.02192495e-03, 3.75858806e-02, 8.05566460e-03,
        6.19262695e-01, 3.91988941e-02],
       [2.76140124e-03, 

In [67]:
import numpy as np
# cifar-10 : (60000, 32, 32), (60000)
# cifar-100 : (60000, 32, 32), (60000)
# X_test : (10000, 32, 32)
# Y_test : (10000, 10)
print(X_test.shape)
print(Y_test.shape)
Y_test0 = np.full((10000, 10), 0.1)
score0 = model.evaluate(X_test, Y_test0)

#CIFAR-100のデータセットのインポート
from keras.datasets import cifar100
(X_train2, Y_train2), (X_test2, Y_test2) = cifar100.load_data()
#CIFAR-100の正規化
from keras.utils import to_categorical
# 特徴量の正規化
X_train2 = X_train2/255.
X_test2 = X_test2/255.
 
# クラスラベルの1-hotベクトル化
Y_train2 = to_categorical(Y_train2, 100)
Y_test2 = to_categorical(Y_test2, 100)

score2 = model.evaluate(X_test2, Y_test0)

(10000, 32, 32, 3)
(10000, 10)
313/313 [==============================] - 13s 42ms/step - loss: 4.8598 - accuracy: 0.0778


In [102]:
# cifar-10, cifar-100からそれぞれ100ずつデータを取ってきている。
# x_judge : (200, 3072) : 予測精度確認用の画像の入力データセット
# y_test0 : 200個のデータセットに対して、[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1] を並べたもの。
# y_test0はcifar-10における10クラス分類の予測の確信度が低い場合の極端な例で、これとのlossが少ないものほど予測の確信度が低い。
# cifar-10の中での10クラス分類がうまくいかないと言える。これはcifar-100のデータである可能性が高い。
# したがって、lossの値を適切に選べば精度良くcifar-100を識別する事ができる可能性がある。

y_test0 = np.full((200, 10), 0.1)
y_test03_3= np.full((200, 10), 0.0)
y_test05_2= np.full((200, 10), 0.0)
x_judge = np.zeros((200, 32, 32, 3))
x_judge[0:100,:,:,:] = X_test[0:100,:,:,:]
x_judge[100:,:,:,:] = X_test2[100:200,:,:,:]

# y_judge : (20000,)
y_judge = np.full(200, 0)
y_judge[100:] = np.full(100, 1)

In [104]:
# 10か100かの予測が実際と一致するものの数をcntとして全体の数200で割っている。
cnt=0.0
j = np.zeros(200)
#for i in range(200) :
#    loss = model.evaluate(x_judge[i:i+1,:,:,:], y_test0[i:i+1,:], verbose=0)
#    if loss[0]<5.0 :
#        j[i] =1
for i_x in range(10):
    for i_y in range(10):
        for i_z in range(10):
            #if (i_x == i_y) continue
            #if (i_y == i_z) continue
            #if (i_z == i_x) continue
            y_test03_3[:,:]=0.0
            y_test03_3[:,i_x] =0.3
            y_test03_3[:,i_y] =0.3
            y_test03_3[:,i_z] =0.3
            for i in range(200) :
                loss = model.evaluate(x_judge[i:i+1,:,:,:], y_test03_3[i:i+1,:], verbose=0)
                if loss[0]<6.0 :
                    j[i] =1
for i in range(200) :
    if((j[i]+y_judge[i])%2==0):
        cnt+=1.0
ans = cnt / 200
print(ans)

KeyboardInterrupt: 

In [ ]:
# 10か100かの予測が実際と一致するものの数をcntとして全体の数200で割っている。
cnt=0.0
j = np.zeros(200)
#for i in range(200) :
#    loss = model.evaluate(x_judge[i:i+1,:,:,:], y_test0[i:i+1,:], verbose=0)
#    if loss[0]<5.0 :
#        j[i] =1
for i_x in range(10):
    for i_y in range(10):
        for i_z in range(10):
            #if (i_x == i_y) continue
            #if (i_y == i_z) continue
            #if (i_z == i_x) continue
            y_test03_3[:,:]=0.0
            y_test03_3[:,i_x] =0.3
            y_test03_3[:,i_y] =0.3
            y_test03_3[:,i_z] =0.3
            for i in range(200) :
                loss = model.evaluate(x_judge[i:i+1,:,:,:], y_test03_3[i:i+1,:], verbose=0)
                if loss[0]<5.0 :
                    j[i] =1
for i in range(200) :
    if((j[i]+y_judge[i])%2==0):
        cnt+=1.0
ans = cnt / 200
print(ans)

In [105]:
# y_judge : (200,)
y_judge = np.full(200, 0)
y_judge[100:] = np.full(100, 1)
# y_test1_10 : (200, 10)
y_test1_10= np.full((200, 10), 0.0)
# 10か100かの予測が実際と一致するものの数をcntとして全体の数200で割っている。
cnt=0.0
j = np.full(200, 1)
#for i in range(200) :
#    loss = model.evaluate(x_judge[i:i+1,:,:,:], y_test0[i:i+1,:], verbose=0)
#    if loss[0]<5.0 :
#        j[i] =1
for i_x in range(10):
            y_test1_10[:,:]=0.0
            y_test1_10[:,i_x] = 1.0
            for i in range(200) :
                loss = model.evaluate(x_judge[i:i+1,:,:,:], y_test1_10[i:i+1,:], verbose=0)
                if loss[0]<0.5 :
                    j[i] = 0


In [107]:
cnt_1 = 0.0
cnt_2 = 0.0
for i in range(100) :
    print(j[i])
    print(y_judge[i])
    if(j[i] == y_judge[i]):
        cnt_1+=1.0
for i in range(100) :
    print(j[i+100])
    print(y_judge[i+100])
    if(j[i+100] == y_judge[i+100]):
        cnt_2+=1.0
ans_1 = cnt_1 / 100
ans_2 = cnt_2 / 100
ans = (cnt_1+cnt_2) / 200
print(ans_1)
print(ans_2)
print(ans)

0
0
0
0
0
0
1
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
1
0
0
0
0
0
1
0
1
0
1
0
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
1
0
0
1
0
1
0
1
0
1
1
1
0
1
1
1
1
1
1
1
1
1
1
1
1
1
0
1
1
1
0
1
1
1
0
1
0
1
1
1
0
1
0
1
1
1
0
1
0
1
1
1
1
1
1
1
0
1
1
1
1
1
0
1
1
1
0
1
0
1
0
1
0
1
1
1
1
1
1
1
1
1
0
1
1
1
0
1
0
1
0
1
0
1
0
1
0
1
1
1
0
1
1
1
1
1
1
1
1
1
0
1
0
1
0
1
0
1
1
1
1
1
1
1
0
1
0
1
1
1
0
1
0
1
1
1
0
1
1
1
1
1
1
1
0
1
0
1
1
1
0
1
0
1
1
1
0
1
1
1
0
1
1
1
1
1
1
1
0
1
1
1
0
1
1
1
1
1
1
1
1
1
0
1
0
1
0
1
0
1
0
1
1
1
0
1
0
1
1
1
0
1
0.79
0.48
0.635


In [ ]:
# [1.0,0.0, ... , 0.0], loss < 0.5 : cifar-10...0.79, cifar-100... 0.48

In [116]:
# CNNの構築
import keras
from keras.models import Sequential
from keras.layers.convolutional import Conv2D, MaxPooling2D
from keras.layers.core import Dense, Dropout, Activation, Flatten
from keras.layers import GlobalAveragePooling2D
from keras.layers.normalization import BatchNormalization
import numpy as np
 
model = Sequential()
 
model.add(Conv2D(32, (3, 3), padding='same',input_shape=X_train.shape[1:]))
model.add(Activation('relu'))
model.add(BatchNormalization())
model.add(Conv2D(32, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
 
model.add(Conv2D(64, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(BatchNormalization())
model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Conv2D(128, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(Conv2D(128, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Conv2D(256, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(Conv2D(256, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(BatchNormalization())

model.add(Conv2D(512, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(Conv2D(512, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(GlobalAveragePooling2D())

model.add(Flatten())
model.add(Dense(1024))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(10))
model.add(Activation('softmax'))

In [117]:
# コンパイル
model.compile(loss='categorical_crossentropy',optimizer='SGD',metrics=['accuracy'])
 
#訓練
history = model.fit(X_train, Y_train, epochs=50)

Epoch 1/50
1563/1563 [==============================] - 1327s 849ms/step - loss: 1.7969 - accuracy: 0.3051
Epoch 2/50
1563/1563 [==============================] - 1077s 689ms/step - loss: 1.4049 - accuracy: 0.4819
Epoch 3/50
1563/1563 [==============================] - 762s 488ms/step - loss: 1.2072 - accuracy: 0.5626
Epoch 4/50
1563/1563 [==============================] - 739s 473ms/step - loss: 1.0795 - accuracy: 0.6114
Epoch 5/50
1563/1563 [==============================] - 8102s 5s/step - loss: 0.9901 - accuracy: 0.6457
Epoch 6/50
1563/1563 [==============================] - 776s 497ms/step - loss: 0.9153 - accuracy: 0.6755
Epoch 7/50
1563/1563 [==============================] - 752s 481ms/step - loss: 0.8444 - accuracy: 0.7013
Epoch 8/50
1563/1563 [==============================] - 3643s 2s/step - loss: 0.7934 - accuracy: 0.7221
Epoch 9/50
1563/1563 [==============================] - 727s 465ms/step - loss: 0.7526 - accuracy: 0.7376
Epoch 10/50
1563/1563 [=========================

In [118]:
# モデルの保存
model.save('./CIFAR-10_4.h5')

 #評価 & 評価結果出力
print(model.evaluate(X_test, Y_test))

313/313 [==============================] - 18s 57ms/step - loss: 0.5608 - accuracy: 0.8437
[0.5608178973197937, 0.8436999917030334]


In [127]:
cnt4=0.0
for i in range(100):
    if np.max(model(X_test[i:i+1]))>0.8:
        cnt4+=1.0
print(cnt4/100)
cnt5=0.0
for i in range(100):
    if np.max(model(X_test2[i:i+1]))>0.8:
        cnt5+=1.0
print(cnt5/100)

0.86
0.53


In [125]:
model(X_test2[0:100])

<tf.Tensor: shape=(100, 10), dtype=float32, numpy=
array([[5.90234667e-05, 6.80333230e-08, 9.99398470e-01, 9.04247863e-05,
        2.59307399e-05, 3.97864147e-04, 1.05303161e-05, 1.56619462e-05,
        1.39740575e-06, 5.71665964e-07],
       [6.22917360e-05, 5.42698253e-05, 8.67772941e-03, 9.16078210e-01,
        1.57271083e-02, 5.05208895e-02, 6.45600213e-03, 6.16676465e-04,
        2.40946669e-04, 1.56581239e-03],
       [5.68412384e-03, 1.35177717e-04, 4.90746386e-02, 8.93402379e-03,
        2.95159787e-01, 3.12294415e-03, 6.32981241e-01, 3.59993777e-03,
        8.74341640e-04, 4.33782552e-04],
       [1.00726320e-03, 7.04965461e-03, 6.48717908e-03, 3.61024499e-01,
        4.80551720e-01, 7.30858892e-02, 6.46278337e-02, 4.26339591e-03,
        1.91208514e-04, 1.71138253e-03],
       [1.74319252e-01, 2.85461592e-03, 1.16109103e-02, 2.87815988e-01,
        7.43169561e-02, 1.18551301e-02, 9.09406506e-03, 1.21752860e-03,
        4.23109591e-01, 3.80598917e-03],
       [1.31868366e-02, 

In [126]:
model(X_test[0:100])

<tf.Tensor: shape=(100, 10), dtype=float32, numpy=
array([[2.58325690e-05, 1.06780017e-05, 2.20943475e-04, 9.86294925e-01,
        1.28342755e-04, 7.08670635e-03, 6.15134137e-03, 3.44271211e-05,
        2.19661542e-05, 2.48329907e-05],
       [7.14581867e-04, 2.24711676e-03, 3.66165480e-08, 2.23386039e-07,
        2.08275779e-08, 1.81042541e-08, 3.73433053e-08, 1.64861245e-08,
        9.97031808e-01, 6.13421798e-06],
       [1.81877073e-02, 2.56651621e-02, 2.70418914e-05, 5.42203525e-05,
        1.06068173e-05, 2.64680057e-06, 1.79301423e-05, 5.35470053e-06,
        9.55301344e-01, 7.28019804e-04],
       [9.89950180e-01, 7.80254602e-04, 2.25106793e-04, 3.25978943e-03,
        5.80591259e-05, 4.02726837e-05, 1.90300198e-05, 2.76176816e-05,
        5.58440015e-03, 5.52884048e-05],
       [5.13986720e-07, 1.71705130e-06, 3.25033732e-04, 1.12349540e-03,
        3.27191301e-05, 1.78831203e-06, 9.98509824e-01, 1.64207663e-07,
        2.06239997e-06, 2.66297934e-06],
       [3.59936045e-08, 

In [140]:
# cifar-10, cifar-100からそれぞれ100ずつデータを取ってきている。
# x_judge : (200, 3072) : 予測精度確認用の画像の入力データセット
# y_test0 : 200個のデータセットに対して、[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1] を並べたもの。
# y_test0はcifar-10における10クラス分類の予測の確信度が低い場合の極端な例で、これとのlossが少ないものほど予測の確信度が低い。
# cifar-10の中での10クラス分類がうまくいかないと言える。これはcifar-100のデータである可能性が高い。
# したがって、lossの値を適切に選べば精度良くcifar-100を識別する事ができる可能性がある。

y_test01_10 = np.full((200, 10), 0.1)
x_judge = np.zeros((200, 32, 32, 3))
x_judge[0:100,:,:,:] = X_test[0:100,:,:,:]
x_judge[100:,:,:,:] = X_test2[100:200,:,:,:]
# y_judge : (20000,)
y_judge = np.full(200, 0)
y_judge[100:] = np.full(100, 1)

In [137]:
# y_judge : (200,)
y_judge = np.full(200, 0)
y_judge[100:] = np.full(100, 1)
# y_test1_10 : (200, 10)
y_test1_10= np.full((200, 10), 0.0)
# 10か100かの予測が実際と一致するものの数をcntとして全体の数200で割っている。
cnt=0.0
#j = np.full(200, 0)

In [145]:
#j = j_save
j = np.full(200, 0)
for i in range(200) :
    loss = model.evaluate(x_judge[i:i+1,:,:,:], y_test01_10[i:i+1,:], verbose=0)
    if loss[0]<7.5:
            j[i] =1

In [146]:
#j = j_save
cnt_1 = 0.0
cnt_2 = 0.0
for i in range(100) :
    print(j[i])
    print(y_judge[i])
    if(j[i] == y_judge[i]):
        cnt_1+=1.0
for i in range(100) :
    print(j[i+100])
    print(y_judge[i+100])
    if(j[i+100] == y_judge[i+100]):
        cnt_2+=1.0
ans_1 = cnt_1 / 100
ans_2 = cnt_2 / 100
ans = (cnt_1+cnt_2) / 200
print(ans_1)
print(ans_2)
print(ans)

0
0
0
0
0
0
0
0
0
0
0
0
1
0
1
0
0
0
0
0
1
0
0
0
1
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
1
0
1
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
1
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
1
0
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
1
0
1
1
1
1
1
1
0
1
1
1
1
1
1
1
1
1
0
1
1
1
1
1
1
1
0
1
1
1
0
1
1
1
1
1
1
1
1
1
0
1
0
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
0
1
0
1
1
1
0
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
0
1
1
1
1
1
0
1
1
1
1
1
1
1
0
1
0
1
1
1
1
1
1
1
1
1
1
1
0
1
1
1
1
1
1
1
0
1
1
1
1
1
1
1
0
1
1
1
1
1
0
1
1
1
1
1
1
1
1
1
1
1
1
1
0
1
1
1
1
1
0
1
1
1
1
1
1
1
1
1
1
1
0
1
1
1
1
1
1
1
1
1
1
1
1
1
0
1
1
1
1
1
0
1
1
1
1
1
0
1
1
1
1
1
1
1
0.76
0.77
0.765


In [148]:
# y_test01_10_20000 : 20000個のデータセットに対して、[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1] を並べたもの。
y_test01_10_2000 = np.full((2000, 10), 0.1)
# x_judge2 : (2000, 3072) : 予測精度確認用の画像の入力データセット
x_judge2 = np.zeros((2000, 32, 32, 3))
# cifar-10, cifar-100からそれぞれ100ずつデータを取ってきている。
x_judge2[0:1000,:,:,:] = X_test[0:1000,:,:]
x_judge2[1000:,:,:,:] = X_test2[1000:2000,:,:]
# y_judge2 : (2000,) : 今回前半の100個がcifar-10(0とする)、残りの100個がcifar-100(1とする)としている。
y_judge2 = np.full(2000, 0)
y_judge2[1000:] = np.full(1000, 1)

In [156]:
# y_test10_1_2000 : (2000, 10) ([0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0]のように0を9個、1.0を1個並べたものを2000個並べたもの)
y_test10_1_2000 = np.full((2000, 10), 0.0)
# 初めにすべてを1(cifar-100)と設定する。
j = np.full(2000, 1)
# 10個それぞれの要素の一つ一つが1.0になる場合にlossがk以下のものを0つまり(cifar-10)と適宜変えていく。
for i_x in range(10):
            y_test10_1_2000[:,:]=0.0
            y_test10_1_2000[:,i_x] = 1.0
            for i in range(2000) :
                loss = model.evaluate(x_judge2[i:i+1,:,:,:], y_test10_1_2000[i:i+1,:], verbose=0)
                if loss[0]<0.035 :
                    j[i] = 0

In [157]:
cnt_1 = 0.0
cnt_2 = 0.0
for i in range(1000) :
    #print(j[i])
    #print(y_judge[i])
    if(j[i] == y_judge2[i]):
        cnt_1+=1.0
for i in range(1000) :
    #print(j[i+1000])
    #print(y_judge[i+1000])
    if(j[i+1000] == y_judge2[i+1000]):
        cnt_2+=1.0
ans_1 = cnt_1 / 1000
ans_2 = cnt_2 / 1000
ans = (cnt_1+cnt_2) / 2000
print("cifar-10 accracy :",ans_1)
print("cifar-100 accracy :",ans_2)
print("accuracy :",ans)

cifar-10 accracy : 0.722
cifar-100 accracy : 0.748
accuracy : 0.735


In [ ]:
# k = 0.04, cifar-10 : 0.722, cifar-100 : 0.748, accuracy : 0.7375
# k = 0.035, cifar-10 : 0.695, cifar-100 : 0.788, accuracy : 0.7415
# k = 0.03, cifar-10 : 0.695, cifar-100 : 0.788, accuracy : 0.7415
# k = 0.02, cifar-10 : 0.654, cifar-100 : 0.826, accuracy : 0.74
# k = 0.02, cifar-10 : 0.598, cifar-100 : 0.877, accuracy : 0.7375